theme: jekyll-theme-midnight
title: Simulating Language
description: Academic year 2024-2025
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - index.md
